clear
python run.py > log_error.txt
